const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('masterChief', {
  getProviderStatus: () => ipcRenderer.invoke('provider-status'),
  getCredentialStatus: () => ipcRenderer.invoke('credential-status'),
  getModelCatalog: () => ipcRenderer.invoke('model-catalog'),
  getConnectorStatus: () => ipcRenderer.invoke('connector-status'),
  voiceSelfTest: () => ipcRenderer.invoke('voice-self-test'),
  voiceSetup: () => ipcRenderer.invoke('voice-setup'),
  requestMicrophoneAccess: () => ipcRenderer.invoke('request-microphone-access'),
  openMicrophoneSettings: () => ipcRenderer.invoke('open-microphone-settings'),
  getToolApprovals: () => ipcRenderer.invoke('tool-approvals'),
  setToolApproval: (id, approved) => ipcRenderer.invoke('set-tool-approval', { id, approved }),
  executeLocalTool: id => ipcRenderer.invoke('execute-local-tool', { id }),
  generateLocalMedia: payload => ipcRenderer.invoke('generate-local-media', payload),
  listGeneratedMedia: limit => ipcRenderer.invoke('list-generated-media', { limit }),
  listMediaJobs: limit => ipcRenderer.invoke('media-job-list', { limit }),
  getMediaJob: requestId => ipcRenderer.invoke('media-job-get', { requestId }),
  getMediaCatalog: () => ipcRenderer.invoke('media-catalog'),
  cancelMediaJob: requestId => ipcRenderer.invoke('media-job-cancel', { requestId }),
  retryMediaJob: requestId => ipcRenderer.invoke('media-job-retry', { requestId }),
  duplicateMediaJob: requestId => ipcRenderer.invoke('media-job-duplicate', { requestId }),
  resumeMediaJob: requestId => ipcRenderer.invoke('media-job-resume', { requestId }),
  onMediaJobEvent: callback => { const listener = (_event, data) => callback(data); ipcRenderer.on('media-job-event', listener); return () => ipcRenderer.removeListener('media-job-event', listener); },
  openMediaArchive: () => ipcRenderer.invoke('open-media-archive'),
  clearCreativeSession: payload => ipcRenderer.invoke('clear-creative-session', payload),
  referenceStudioState: () => ipcRenderer.invoke('reference-studio-state'),
  saveReferenceProject: payload => ipcRenderer.invoke('reference-studio-save-project', payload),
  saveReferenceShot: payload => ipcRenderer.invoke('reference-studio-save-shot', payload),
  removeReferenceShot: payload => ipcRenderer.invoke('reference-studio-remove-shot', payload),
  runAgentPlan: payload => ipcRenderer.invoke('run-agent-plan', payload),
  chat: payload => ipcRenderer.invoke('chat', payload),
  onChatEvent: callback => { const listener = (_event, data) => callback(data); ipcRenderer.on('chat-event', listener); return () => ipcRenderer.removeListener('chat-event', listener); },
  cancelChat: () => ipcRenderer.invoke('cancel-chat'),
  transcribeAudio: (audio, type) => ipcRenderer.invoke('transcribe-audio', { audio, type }),
  indexDocument: (name, text) => ipcRenderer.invoke('index-document', { name, text }),
  removeIndexedDocument: name => ipcRenderer.invoke('remove-indexed-document', { name }),
  searchIndex: query => ipcRenderer.invoke('search-index', { query }),
  indexStats: () => ipcRenderer.invoke('index-stats'),
  openArtifact: relativePath => ipcRenderer.invoke('open-artifact', relativePath),
  revealArtifact: relativePath => ipcRenderer.invoke('reveal-artifact', relativePath),
  artifactMetadata: relativePath => ipcRenderer.invoke('artifact-metadata', relativePath),
  previewArtifact: relativePath => ipcRenderer.invoke('preview-artifact', relativePath),
  saveArtifactAs: relativePath => ipcRenderer.invoke('save-artifact-as', relativePath),
  windowAction: action => ipcRenderer.invoke('window-action', action)
});
