const $=id=>document.getElementById(id);const app=$('app'),chat=$('chat'),promptEl=$('prompt'),sendBtn=$('sendBtn'),modelSelect=$('modelSelect'),statusDot=$('statusDot'),holoImg=$('holoImg'),holoStatus=$('holoStatus');
const histories=JSON.parse(localStorage.getItem('masterChiefHistories')||'{}');let busy=false,state='idle',themeMode=localStorage.getItem('mcTheme')||'auto',health={};
const asset={day:{idle:'day_idle.jpg',ready:'day_ready.jpg',listening:'day_ready.jpg',thinking:'day_thinking.jpg',speaking:'day_wave.jpg',success:'day_success.jpg',error:'day_thinking.jpg',wave:'day_wave.jpg'},night:{idle:'night_idle.jpg',ready:'night_idle.jpg',listening:'night_listening.jpg',thinking:'night_thinking.jpg',speaking:'night_speaking.jpg',success:'night_success.jpg',error:'night_alert.jpg',wave:'night_wave.jpg'}};
const labels={idle:'Standing by',ready:'Ready for orders',listening:'Listening',thinking:'Analyzing command',speaking:'Reporting',success:'Mission complete',error:'Action needed',wave:'Hologram online'};
function activeTheme(){if(themeMode!=='auto')return themeMode;const h=new Date().getHours();return h>=7&&h<19?'day':'night'}
function setState(next,force=false){state=next;const src=`assets/drive/${asset[activeTheme()][next]||asset[activeTheme()].idle}`;if(force||!holoImg.src.endsWith(src)){const pre=new Image();pre.onload=()=>{holoImg.src=src};pre.onerror=()=>{holoImg.src='assets/drive/original_mascot.png'};pre.src=src}const label=labels[next]||labels.idle;holoStatus.textContent=label;$('holoStage').setAttribute('aria-label',`Master Chief: ${label}. Activate to focus command input.`);holoImg.alt=`Master Chief hologram ${label.toLowerCase()}`}
function applyTheme(){app.dataset.theme=activeTheme();document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===themeMode)));setState(state,true)}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{themeMode=b.dataset.mode;localStorage.setItem('mcTheme',themeMode);applyTheme()});setInterval(()=>{if(themeMode==='auto'&&!busy)applyTheme()},60000);
function getHistory(p){return histories[p]||(histories[p]=[])}function save(){localStorage.setItem('masterChiefHistories',JSON.stringify(histories))}
function addMsg(role,text,meta=''){const d=document.createElement('div');d.className=`msg ${role}`;if(meta){const m=document.createElement('div');m.className='meta';m.textContent=meta;d.append(m)}d.append(document.createTextNode(text));chat.append(d);chat.scrollTop=chat.scrollHeight}
function renderHistory(){chat.replaceChildren();const h=getHistory(modelSelect.value);if(!h.length)addMsg('system','Hologram online. Issue a command, Commander.');else h.forEach(m=>addMsg(m.role==='assistant'?'bot':'user',m.content,m.role==='assistant'?modelSelect.options[modelSelect.selectedIndex].text:''))}
function setBusy(v){busy=v;statusDot.classList.toggle('busy',v);sendBtn.textContent=v?'CANCEL':'TRANSMIT';modelSelect.disabled=v}
function renderHealth(s){if(!s)return;health=s;$('providerHealth').replaceChildren();let ready=0;['codex','openai','grok','github'].forEach(k=>{const x=s[k],c=document.createElement('span');c.className=`health-chip ${x.state}`;c.textContent=x.label;$('providerHealth').append(c);if(x.state==='ready')ready++});$('healthSummary').textContent=`Systems · ${ready} ready · click for details`;$('versionHint').textContent=`v${s.version} · Local history · ⌘Enter to send`;$('versionTitle').textContent=`v${s.version}`;statusDot.style.background=s[modelSelect.value]?.state==='ready'?'#35c96b':'#d99a22'}
async function refreshHealth(){try{renderHealth(await window.masterChief.getProviderStatus())}catch{$('healthSummary').textContent='System check unavailable'}}
async function transmit(){if(busy){await window.masterChief.cancelChat();setBusy(false);setState('ready');addMsg('system','Command cancelled.');return}const text=promptEl.value.trim();if(!text){setState('listening');promptEl.focus();return}const p=modelSelect.value,h=getHistory(p);promptEl.value='';addMsg('user',text);setBusy(true);setState('thinking');try{const result=await window.masterChief.chat({provider:p,messages:[...h,{role:'user',content:text}],masterMode:$('masterMode').checked});setState('speaking');h.push({role:'user',content:text},{role:'assistant',content:result.reply});if(h.length>24)h.splice(0,h.length-24);save();addMsg('bot',result.reply,result.label);setTimeout(()=>{setState('success');setTimeout(()=>setState('idle'),1800)},350)}catch(e){setState('error');addMsg('system',`Connection error: ${e.message}`)}finally{setBusy(false)}}
$('holoStage').onclick=()=>{if(!busy)setState('listening');promptEl.focus()};promptEl.onfocus=()=>{if(!busy)setState('listening')};promptEl.onblur=()=>{if(!busy&&state==='listening')setState('ready')};sendBtn.onclick=transmit;promptEl.onkeydown=e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();transmit()}};
modelSelect.onchange=()=>{renderHistory();renderHealth(health)};$('clearBtn').onclick=()=>{histories[modelSelect.value]=[];save();renderHistory();setState('ready')};$('closeBtn').onclick=()=>window.masterChief.windowAction('hide');$('minBtn').onclick=()=>window.masterChief.windowAction('minimize');$('pinBtn').onclick=async e=>e.currentTarget.setAttribute('aria-pressed',String(await window.masterChief.windowAction('toggle-top')));
applyTheme();renderHistory();const today=new Date().toDateString();if(localStorage.getItem('mcWave')!==today){localStorage.setItem('mcWave',today);setState('wave');setTimeout(()=>setState('idle'),1800)}refreshHealth();
