'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {JOB_KINDS,JOB_EVENTS,CAPABILITIES,createJobRequest,typedJobError}=require('../job-contract');
const {createJobOrchestrator}=require('../job-orchestrator');const {createProviderGateway}=require('../provider-gateway');
function temp(){return path.join(fs.mkdtempSync(path.join(os.tmpdir(),'mc-p0-jobs-')),'jobs.json')}
test('P0 uses one versioned request and event vocabulary for every work type',()=>{assert.deepEqual(JOB_KINDS,['chat','agent','research','artifact','image','video','audio','code','data']);assert.deepEqual(JOB_EVENTS,['accepted','routing','planning','waiting','executing','tool','generating','validating','transferring','complete','failed','cancelled']);assert.equal(createJobRequest({kind:'data',objective:'analyze'}).schemaVersion,1);assert.deepEqual(CAPABILITIES,['chat','reason','code','vision','tools','embedding','rerank','image','video','speech'])});
test('P0 orchestrator is idempotent, durable, resumable, steerable, and preserves receipts',()=>{const file=temp(),store=createJobOrchestrator(file);const first=store.submit({kind:'agent',objective:'build',idempotencyKey:'same'});assert.equal(store.submit({kind:'agent',objective:'duplicate',idempotencyKey:'same'}).created,false);store.setPlan(first.job.request.requestId,[{id:'one',title:'Inspect',stopCondition:'evidence exists'},{id:'two',title:'Build'}]);store.checkpoint(first.job.request.requestId,'one','receipt-1');store.action(first.job.request.requestId,'pause');store.action(first.job.request.requestId,'steer',{steering:'Prefer local'});assert.equal(createJobOrchestrator(file).get(first.job.request.requestId).status,'recoverable');assert.equal(createJobOrchestrator(file).get(first.job.request.requestId).plan[0].evidence,'receipt-1')});
test('P0 gateway routes on capability, privacy, runtime evidence, latency, and memory with explanations',()=>{const gateway=createProviderGateway();const request=createJobRequest({kind:'code',capabilities:['code','tools'],privacy:'local'});const result=gateway.route(request,{ollama:{available:true,latencyMs:80,memoryPressure:.2,model:'qwen'},vllm:{available:false}});assert.equal(result.selected.provider,'ollama');assert.equal(result.selected.model,'qwen');assert.match(result.reason,/measured fit/i);assert.ok(result.candidates.find(item=>item.provider==='gemini').rejected.includes('cloud not explicitly selected'))});
test('P0 failures are typed with one-click recovery contracts',()=>{assert.equal(typedJobError(new Error('runtime not configured')).recovery,'configure');assert.equal(typedJobError(new Error('network connection failed')).recovery,'reconnect');assert.equal(typedJobError(new Error('select a model')).recovery,'select-model')});
test('P0 UI exposes Job Center, filters, routing explanations, drafts, steering, outputs, files, and keyboard access',()=>{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),renderer=fs.readFileSync(path.join(__dirname,'..','renderer.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'..','styles.css'),'utf8');for(const value of ['Job Center','jobStatusFilter','Files','Outputs','commandPalette'])assert.match(html,new RegExp(value));for(const value of ['masterChiefComposerDraftV1','Why this model','jobAction','Open Job Center','ArrowRight','attachmentNames'])assert.match(renderer,new RegExp(value));assert.match(css,/job-plan/);assert.match(css,/max-width:900px/) });
test('P0 packaging includes the orchestrator boundary and provider gateway',()=>{const pkg=require('../package.json');for(const name of ['job-contract.js','job-orchestrator.js','provider-gateway.js'])assert.ok(pkg.build.files.includes(name));assert.ok(Number(pkg.version.split('.')[1])>=43)});
