'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');
const {createRepositoryIndexer}=require('../repository-index');const {validateExtensionManifest,discoverRecipes,SDK_VERSION}=require('../extension-sdk');const {publicResearchUrls,normalizeResearchOptions,normalizeSearxng}=require('../public-research');const {createConversationStore}=require('../conversation-store');const {runCapabilityGapAudit}=require('../capability-gap-audit');
function temp(){return fs.mkdtempSync(path.join(os.tmpdir(),'mc-p2-'))}
test('P2 repository indexing preserves branch ref path and content hash provenance',async()=>{const root=temp();fs.writeFileSync(path.join(root,'README.md'),'alpha evidence');fs.writeFileSync(path.join(root,'binary.bin'),Buffer.from([0,1]));const indexed=[];const execFile=async(_bin,args)=>({stdout:args[0]==='branch'?'main\n':args[0]==='rev-parse'?'a'.repeat(40):'README.md\nbinary.bin\n'});const run=createRepositoryIndexer({root,execFile,indexDocument:(name,text,options)=>indexed.push({name,text,options})});const result=await run();assert.equal(result.indexed,1);assert.equal(indexed[0].options.provenance.branch,'main');assert.equal(indexed[0].options.provenance.revision,'a'.repeat(40));assert.match(indexed[0].options.provenance.sha256,/^[a-f0-9]{64}$/)});
test('P2 research filters constrain domains and freshness',()=>{assert.deepEqual(normalizeResearchOptions({domains:['Example.com','bad value'],freshness:'week'}),{domains:['example.com'],freshness:'week'});const urls=publicResearchUrls('release evidence',{domains:['example.com'],freshness:'month'});assert.match(urls.searxng,/time_range=month/);const result=normalizeSearxng('x',{results:[{title:'Keep',url:'https://docs.example.com/a',content:'ok'},{title:'Drop',url:'https://other.test/b',content:'no'}]},{domains:['example.com']});assert.equal(result.sources.length,1)});
test('P2 conversation JSON and Markdown are portable with bounded import',()=>{const file=path.join(temp(),'threads.json');const store=createConversationStore(file);const saved=store.upsert({title:'Portable',messages:[{role:'user',content:'hello'},{role:'assistant',content:'world'}]});assert.match(store.exportData(saved.id,'markdown'),/# Portable/);const json=store.exportData(null,'json');const other=createConversationStore(path.join(temp(),'other.json'));assert.equal(other.importData(json).imported,1);assert.equal(other.list({includeMessages:true})[0].messages[0].content,'hello')});
test('P2 extension SDK rejects unreviewed capability escalation',()=>{const valid=validateExtensionManifest({id:'local.test.recipe',name:'Test',version:'1.0.0',sdkVersion:SDK_VERSION,capabilities:['provider.recipe']});assert.equal(valid.id,'local.test.recipe');assert.throws(()=>validateExtensionManifest({...valid,capabilities:['shell.unrestricted']}),/unsupported capability/);assert.equal(discoverRecipes(path.join(__dirname,'..','recipes')).length>=1,true)});
test('P2 capability comparison returns a weighted prioritized build list',()=>{const report=runCapabilityGapAudit();assert.equal(report.areas.length,10);assert.equal(report.parity,false);assert.equal(report.buildList.length,10);assert.ok(report.score>=75&&report.score<100);for(let i=1;i<report.buildList.length;i++)assert.ok(report.buildList[i].priority>report.buildList[i-1].priority)});
test('P2 UI exposes ensemble, repository, memory review, portability, and extension recipes',()=>{const renderer=fs.readFileSync(path.join(__dirname,'..','renderer.js'),'utf8');const preload=fs.readFileSync(path.join(__dirname,'..','preload.js'),'utf8');for(const token of ['runEnsembleCommand','repositoryIndexBtn','extractMemoryBtn','conversationImportBtn','extensionRecipesBtn'])assert.match(renderer,new RegExp(token));for(const token of ['runEnsemble','indexRepository','getMemoryCandidates','exportConversations','listExtensionRecipes'])assert.match(preload,new RegExp(token))});
